# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: geometry.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0egeometry.proto\x12\x08geometry\"<\n\nCoordinate\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\r\n\x05has_z\x18\x04 \x01(\x08\"{\n\x08Geometry\x12\x1c\n\x04type\x18\x01 \x01(\x0e\x32\x0e.geometry.Type\x12)\n\x0b\x63oordinates\x18\x02 \x03(\x0b\x32\x14.geometry.Coordinate\x12&\n\ngeometries\x18\x03 \x03(\x0b\x32\x12.geometry.Geometry*\xa5\x01\n\x04Type\x12\t\n\x05POINT\x10\x00\x12\x0e\n\nLINESTRING\x10\x01\x12\x0b\n\x07POLYGON\x10\x02\x12\x0e\n\nMULTIPOINT\x10\x03\x12\x13\n\x0fMULTILINESTRING\x10\x04\x12\x10\n\x0cMULTIPOLYGON\x10\x05\x12\x08\n\x04LINE\x10\x06\x12\x0c\n\x08TRIANGLE\x10\x07\x12\x0e\n\nLINEARRING\x10\x08\x12\x16\n\x12GEOMETRYCOLLECTION\x10\tb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'geometry_pb2', _globals)
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _globals['_TYPE']._serialized_start=216
  _globals['_TYPE']._serialized_end=381
  _globals['_COORDINATE']._serialized_start=28
  _globals['_COORDINATE']._serialized_end=88
  _globals['_GEOMETRY']._serialized_start=90
  _globals['_GEOMETRY']._serialized_end=213
# @@protoc_insertion_point(module_scope)
