# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: geometry.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import enum_type_wrapper
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database

# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


DESCRIPTOR = _descriptor.FileDescriptor(
    name="geometry.proto",
    package="geometry",
    syntax="proto3",
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
    serialized_pb=b'\n\x0egeometry.proto\x12\x08geometry"<\n\nCoordinate\x12\t\n\x01x\x18\x01 \x01(\x01\x12\t\n\x01y\x18\x02 \x01(\x01\x12\t\n\x01z\x18\x03 \x01(\x01\x12\r\n\x05has_z\x18\x04 \x01(\x08"{\n\x08Geometry\x12\x1c\n\x04type\x18\x01 \x01(\x0e\x32\x0e.geometry.Type\x12)\n\x0b\x63oordinates\x18\x02 \x03(\x0b\x32\x14.geometry.Coordinate\x12&\n\ngeometries\x18\x03 \x03(\x0b\x32\x12.geometry.Geometry*\xa5\x01\n\x04Type\x12\t\n\x05POINT\x10\x00\x12\x0e\n\nLINESTRING\x10\x01\x12\x0b\n\x07POLYGON\x10\x02\x12\x0e\n\nMULTIPOINT\x10\x03\x12\x13\n\x0fMULTILINESTRING\x10\x04\x12\x10\n\x0cMULTIPOLYGON\x10\x05\x12\x08\n\x04LINE\x10\x06\x12\x0c\n\x08TRIANGLE\x10\x07\x12\x0e\n\nLINEARRING\x10\x08\x12\x16\n\x12GEOMETRYCOLLECTION\x10\tb\x06proto3',
)

_TYPE = _descriptor.EnumDescriptor(
    name="Type",
    full_name="geometry.Type",
    filename=None,
    file=DESCRIPTOR,
    create_key=_descriptor._internal_create_key,
    values=[
        _descriptor.EnumValueDescriptor(
            name="POINT",
            index=0,
            number=0,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="LINESTRING",
            index=1,
            number=1,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="POLYGON",
            index=2,
            number=2,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="MULTIPOINT",
            index=3,
            number=3,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="MULTILINESTRING",
            index=4,
            number=4,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="MULTIPOLYGON",
            index=5,
            number=5,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="LINE",
            index=6,
            number=6,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="TRIANGLE",
            index=7,
            number=7,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="LINEARRING",
            index=8,
            number=8,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.EnumValueDescriptor(
            name="GEOMETRYCOLLECTION",
            index=9,
            number=9,
            serialized_options=None,
            type=None,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    containing_type=None,
    serialized_options=None,
    serialized_start=216,
    serialized_end=381,
)
_sym_db.RegisterEnumDescriptor(_TYPE)

Type = enum_type_wrapper.EnumTypeWrapper(_TYPE)
POINT = 0
LINESTRING = 1
POLYGON = 2
MULTIPOINT = 3
MULTILINESTRING = 4
MULTIPOLYGON = 5
LINE = 6
TRIANGLE = 7
LINEARRING = 8
GEOMETRYCOLLECTION = 9


_COORDINATE = _descriptor.Descriptor(
    name="Coordinate",
    full_name="geometry.Coordinate",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="x",
            full_name="geometry.Coordinate.x",
            index=0,
            number=1,
            type=1,
            cpp_type=5,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="y",
            full_name="geometry.Coordinate.y",
            index=1,
            number=2,
            type=1,
            cpp_type=5,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="z",
            full_name="geometry.Coordinate.z",
            index=2,
            number=3,
            type=1,
            cpp_type=5,
            label=1,
            has_default_value=False,
            default_value=float(0),
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="has_z",
            full_name="geometry.Coordinate.has_z",
            index=3,
            number=4,
            type=8,
            cpp_type=7,
            label=1,
            has_default_value=False,
            default_value=False,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=28,
    serialized_end=88,
)


_GEOMETRY = _descriptor.Descriptor(
    name="Geometry",
    full_name="geometry.Geometry",
    filename=None,
    file=DESCRIPTOR,
    containing_type=None,
    create_key=_descriptor._internal_create_key,
    fields=[
        _descriptor.FieldDescriptor(
            name="type",
            full_name="geometry.Geometry.type",
            index=0,
            number=1,
            type=14,
            cpp_type=8,
            label=1,
            has_default_value=False,
            default_value=0,
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="coordinates",
            full_name="geometry.Geometry.coordinates",
            index=1,
            number=2,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
        _descriptor.FieldDescriptor(
            name="geometries",
            full_name="geometry.Geometry.geometries",
            index=2,
            number=3,
            type=11,
            cpp_type=10,
            label=3,
            has_default_value=False,
            default_value=[],
            message_type=None,
            enum_type=None,
            containing_type=None,
            is_extension=False,
            extension_scope=None,
            serialized_options=None,
            file=DESCRIPTOR,
            create_key=_descriptor._internal_create_key,
        ),
    ],
    extensions=[],
    nested_types=[],
    enum_types=[],
    serialized_options=None,
    is_extendable=False,
    syntax="proto3",
    extension_ranges=[],
    oneofs=[],
    serialized_start=90,
    serialized_end=213,
)

_GEOMETRY.fields_by_name["type"].enum_type = _TYPE
_GEOMETRY.fields_by_name["coordinates"].message_type = _COORDINATE
_GEOMETRY.fields_by_name["geometries"].message_type = _GEOMETRY
DESCRIPTOR.message_types_by_name["Coordinate"] = _COORDINATE
DESCRIPTOR.message_types_by_name["Geometry"] = _GEOMETRY
DESCRIPTOR.enum_types_by_name["Type"] = _TYPE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Coordinate = _reflection.GeneratedProtocolMessageType(
    "Coordinate",
    (_message.Message,),
    {
        "DESCRIPTOR": _COORDINATE,
        "__module__": "geometry_pb2"
        # @@protoc_insertion_point(class_scope:geometry.Coordinate)
    },
)
_sym_db.RegisterMessage(Coordinate)

Geometry = _reflection.GeneratedProtocolMessageType(
    "Geometry",
    (_message.Message,),
    {
        "DESCRIPTOR": _GEOMETRY,
        "__module__": "geometry_pb2"
        # @@protoc_insertion_point(class_scope:geometry.Geometry)
    },
)
_sym_db.RegisterMessage(Geometry)


# @@protoc_insertion_point(module_scope)
