# Generated by the protocol buffer compiler.  DO NOT EDIT!
# sources: shapely_grpc_io/geometry.proto
# plugin: python-betterproto
from dataclasses import dataclass
from typing import List

import betterproto


class Type(betterproto.Enum):
    POINT = 0
    LINESTRING = 1
    POLYGON = 2
    MULTIPOINT = 3
    MULTILINESTRING = 4
    MULTIPOLYGON = 5
    LINE = 6
    TRIANGLE = 7
    LINEARRING = 8
    GEOMETRYCOLLECTION = 9


@dataclass
class Coordinate(betterproto.Message):
    x: float = betterproto.double_field(1)
    y: float = betterproto.double_field(2)
    z: float = betterproto.double_field(3)
    has_z: bool = betterproto.bool_field(4)


@dataclass
class Geometry(betterproto.Message):
    type: "Type" = betterproto.enum_field(1)
    coordinates: List["Coordinate"] = betterproto.message_field(2)
    geometries: List["Geometry"] = betterproto.message_field(3)
