# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc

import kenya_wards_pb2 as kenya__wards__pb2


class AdminBoundariesServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetLevel1Boundaries = channel.unary_unary(
                '/AdminBoundariesService/GetLevel1Boundaries',
                request_serializer=kenya__wards__pb2.BoundariesRequest.SerializeToString,
                response_deserializer=kenya__wards__pb2.Level1BoundariesResponse.FromString,
                )
        self.GetLevel2Boundaries = channel.unary_unary(
                '/AdminBoundariesService/GetLevel2Boundaries',
                request_serializer=kenya__wards__pb2.BoundariesRequest.SerializeToString,
                response_deserializer=kenya__wards__pb2.Level2BoundariesResponse.FromString,
                )


class AdminBoundariesServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetLevel1Boundaries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetLevel2Boundaries(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AdminBoundariesServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetLevel1Boundaries': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLevel1Boundaries,
                    request_deserializer=kenya__wards__pb2.BoundariesRequest.FromString,
                    response_serializer=kenya__wards__pb2.Level1BoundariesResponse.SerializeToString,
            ),
            'GetLevel2Boundaries': grpc.unary_unary_rpc_method_handler(
                    servicer.GetLevel2Boundaries,
                    request_deserializer=kenya__wards__pb2.BoundariesRequest.FromString,
                    response_serializer=kenya__wards__pb2.Level2BoundariesResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'AdminBoundariesService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class AdminBoundariesService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetLevel1Boundaries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AdminBoundariesService/GetLevel1Boundaries',
            kenya__wards__pb2.BoundariesRequest.SerializeToString,
            kenya__wards__pb2.Level1BoundariesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def GetLevel2Boundaries(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/AdminBoundariesService/GetLevel2Boundaries',
            kenya__wards__pb2.BoundariesRequest.SerializeToString,
            kenya__wards__pb2.Level2BoundariesResponse.FromString,
            options, channel_credentials,
            insecure, call_credentials, compression, wait_for_ready, timeout, metadata)
