# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: kenya_wards.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


import geometry_pb2 as geometry__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='kenya_wards.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x11kenya_wards.proto\x1a\x0egeometry.proto\"P\n\x0eLevel1Boundary\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12$\n\x08\x62oundary\x18\x03 \x01(\x0b\x32\x12.geometry.Geometry\"b\n\x0eLevel2Boundary\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\x12\x10\n\x08\x61\x64m1name\x18\x03 \x01(\t\x12$\n\x08\x62oundary\x18\x04 \x01(\x0b\x32\x12.geometry.Geometry\"7\n\x11\x42oundariesRequest\x12\"\n\x06\x62ounds\x18\x01 \x01(\x0b\x32\x12.geometry.Geometry\"?\n\x18Level1BoundariesResponse\x12#\n\nboundaries\x18\x01 \x03(\x0b\x32\x0f.Level1Boundary\"?\n\x18Level2BoundariesResponse\x12#\n\nboundaries\x18\x01 \x03(\x0b\x32\x0f.Level2Boundary2\xa4\x01\n\x16\x41\x64minBoundariesService\x12\x44\n\x13GetLevel1Boundaries\x12\x12.BoundariesRequest\x1a\x19.Level1BoundariesResponse\x12\x44\n\x13GetLevel2Boundaries\x12\x12.BoundariesRequest\x1a\x19.Level2BoundariesResponseb\x06proto3'
  ,
  dependencies=[geometry__pb2.DESCRIPTOR,])




_LEVEL1BOUNDARY = _descriptor.Descriptor(
  name='Level1Boundary',
  full_name='Level1Boundary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Level1Boundary.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='Level1Boundary.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='boundary', full_name='Level1Boundary.boundary', index=2,
      number=3, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=37,
  serialized_end=117,
)


_LEVEL2BOUNDARY = _descriptor.Descriptor(
  name='Level2Boundary',
  full_name='Level2Boundary',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='Level2Boundary.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='name', full_name='Level2Boundary.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='adm1name', full_name='Level2Boundary.adm1name', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='boundary', full_name='Level2Boundary.boundary', index=3,
      number=4, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=119,
  serialized_end=217,
)


_BOUNDARIESREQUEST = _descriptor.Descriptor(
  name='BoundariesRequest',
  full_name='BoundariesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='bounds', full_name='BoundariesRequest.bounds', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=274,
)


_LEVEL1BOUNDARIESRESPONSE = _descriptor.Descriptor(
  name='Level1BoundariesResponse',
  full_name='Level1BoundariesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='boundaries', full_name='Level1BoundariesResponse.boundaries', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=276,
  serialized_end=339,
)


_LEVEL2BOUNDARIESRESPONSE = _descriptor.Descriptor(
  name='Level2BoundariesResponse',
  full_name='Level2BoundariesResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='boundaries', full_name='Level2BoundariesResponse.boundaries', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=341,
  serialized_end=404,
)

_LEVEL1BOUNDARY.fields_by_name['boundary'].message_type = geometry__pb2._GEOMETRY
_LEVEL2BOUNDARY.fields_by_name['boundary'].message_type = geometry__pb2._GEOMETRY
_BOUNDARIESREQUEST.fields_by_name['bounds'].message_type = geometry__pb2._GEOMETRY
_LEVEL1BOUNDARIESRESPONSE.fields_by_name['boundaries'].message_type = _LEVEL1BOUNDARY
_LEVEL2BOUNDARIESRESPONSE.fields_by_name['boundaries'].message_type = _LEVEL2BOUNDARY
DESCRIPTOR.message_types_by_name['Level1Boundary'] = _LEVEL1BOUNDARY
DESCRIPTOR.message_types_by_name['Level2Boundary'] = _LEVEL2BOUNDARY
DESCRIPTOR.message_types_by_name['BoundariesRequest'] = _BOUNDARIESREQUEST
DESCRIPTOR.message_types_by_name['Level1BoundariesResponse'] = _LEVEL1BOUNDARIESRESPONSE
DESCRIPTOR.message_types_by_name['Level2BoundariesResponse'] = _LEVEL2BOUNDARIESRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Level1Boundary = _reflection.GeneratedProtocolMessageType('Level1Boundary', (_message.Message,), {
  'DESCRIPTOR' : _LEVEL1BOUNDARY,
  '__module__' : 'kenya_wards_pb2'
  # @@protoc_insertion_point(class_scope:Level1Boundary)
  })
_sym_db.RegisterMessage(Level1Boundary)

Level2Boundary = _reflection.GeneratedProtocolMessageType('Level2Boundary', (_message.Message,), {
  'DESCRIPTOR' : _LEVEL2BOUNDARY,
  '__module__' : 'kenya_wards_pb2'
  # @@protoc_insertion_point(class_scope:Level2Boundary)
  })
_sym_db.RegisterMessage(Level2Boundary)

BoundariesRequest = _reflection.GeneratedProtocolMessageType('BoundariesRequest', (_message.Message,), {
  'DESCRIPTOR' : _BOUNDARIESREQUEST,
  '__module__' : 'kenya_wards_pb2'
  # @@protoc_insertion_point(class_scope:BoundariesRequest)
  })
_sym_db.RegisterMessage(BoundariesRequest)

Level1BoundariesResponse = _reflection.GeneratedProtocolMessageType('Level1BoundariesResponse', (_message.Message,), {
  'DESCRIPTOR' : _LEVEL1BOUNDARIESRESPONSE,
  '__module__' : 'kenya_wards_pb2'
  # @@protoc_insertion_point(class_scope:Level1BoundariesResponse)
  })
_sym_db.RegisterMessage(Level1BoundariesResponse)

Level2BoundariesResponse = _reflection.GeneratedProtocolMessageType('Level2BoundariesResponse', (_message.Message,), {
  'DESCRIPTOR' : _LEVEL2BOUNDARIESRESPONSE,
  '__module__' : 'kenya_wards_pb2'
  # @@protoc_insertion_point(class_scope:Level2BoundariesResponse)
  })
_sym_db.RegisterMessage(Level2BoundariesResponse)



_ADMINBOUNDARIESSERVICE = _descriptor.ServiceDescriptor(
  name='AdminBoundariesService',
  full_name='AdminBoundariesService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=407,
  serialized_end=571,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetLevel1Boundaries',
    full_name='AdminBoundariesService.GetLevel1Boundaries',
    index=0,
    containing_service=None,
    input_type=_BOUNDARIESREQUEST,
    output_type=_LEVEL1BOUNDARIESRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetLevel2Boundaries',
    full_name='AdminBoundariesService.GetLevel2Boundaries',
    index=1,
    containing_service=None,
    input_type=_BOUNDARIESREQUEST,
    output_type=_LEVEL2BOUNDARIESRESPONSE,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_ADMINBOUNDARIESSERVICE)

DESCRIPTOR.services_by_name['AdminBoundariesService'] = _ADMINBOUNDARIESSERVICE

# @@protoc_insertion_point(module_scope)
